### ISSUE TITLE
Bug?: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by stef-rausch** [polyipseity/obsidian-modules#5]
Out of curiosity, I looked at the console while debugging one of my scripts, and I noticed the following error messages:

~~~﻿
plugin:modules:30148 Error: Cannot find module '[[user.script.obsidian.delay-until-synced.mjs]]'
Require stack:
- electron/js2c/renderer_init
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at o._resolveFilename (node:electron/js2c/renderer_init:2:3879)
    at Module._load (node:internal/modules/cjs/loader:927:27)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Gt (app.js:1:262802)
    at o (app.js:1:2033570)
    at e7 (plugin:modules:30146:4867)
plugin:modules:30148 Error: ENOENT: no such file or directory, open 'C:\Users\Stefano F. Rausch\Documents\Obsidian\2Brain\user\[[user.script.obsidian.delay-until-synced.mjs]]'
plugin:modules:30148 Error: ENOENT: no such file or directory, open 'C:\Users\Stefano F. Rausch\Documents\Obsidian\2Brain\[[user.script.obsidian.delay-until-synced.mjs]]'
plugin:modules:30148 Error: Cannot find module '[[user.script.obsidian.delay-until-synced.mjs]]'
Require stack:
- electron/js2c/renderer_init
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at o._resolveFilename (node:electron/js2c/renderer_init:2:3879)
    at Module._load (node:internal/modules/cjs/loader:927:27)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Gt (app.js:1:262802)
    at o (app.js:1:2033570)
    at e7 (plugin:modules:30146:4867)
plugin:modules:30148 Error: ENOENT: no such file or directory, open 'C:\Users\Stefano F. Rausch\Documents\Obsidian\2Brain\user\[[user.script.obsidian.delay-until-synced.mjs]]'
plugin:modules:30148 Error: ENOENT: no such file or directory, open 'C:\Users\Stefano F. Rausch\Documents\Obsidian\2Brain\[[user.script.obsidian.delay-until-synced.mjs]]'
plugin:modules:30148 Error: Cannot find module '[[user.script.obsidian.delay-until-synced.mjs]]'
Require stack:
- electron/js2c/renderer_init
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at o._resolveFilename (node:electron/js2c/renderer_init:2:3879)
    at Module._load (node:internal/modules/cjs/loader:927:27)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Gt (app.js:1:262802)
    at o (app.js:1:2033570)
    at e7 (plugin:modules:30146:4867)
2
plugin:modules:30148 Error: ENOENT: no such file or directory, open 'C:\Users\Stefano F. Rausch\Documents\Obsidian\2Brain\[[user.script.obsidian.delay-until-synced.mjs]]'
plugin:modules:30148 Error: Cannot find module '[[user.script.obsidian.delay-until-synced.mjs]]'
Require stack:
- electron/js2c/renderer_init
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at o._resolveFilename (node:electron/js2c/renderer_init:2:3879)
    at Module._load (node:internal/modules/cjs/loader:927:27)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Gt (app.js:1:262802)
    at o (app.js:1:2033570)
    at e7 (plugin:modules:30146:4867)
2
plugin:modules:30148 Error: ENOENT: no such file or directory, open 'C:\Users\Stefano F. Rausch\Documents\Obsidian\2Brain\[[user.script.obsidian.delay-until-synced.mjs]]'
~~~

Astonishingly, the scripts load -- I use the following format: `await self.require.import("[[wikilink/to/a module|ommited or whatever]]") // wikilink` -- and I can execute them without any issues. Hence, I am wondering why these messages appear in the console.

Do you have any thoughts on that?

**Comment by polyipseity** [comment]
It is normal if those errors are blue in the console.

**Comment by stef-rausch** [comment]
They are "black on white". 😉 

![image](https://github.com/polyipseity/obsidian-modules/assets/1460531/99edb8d2-6448-41b8-b7bd-1d3a6a0a67e9)

Why is it "normal"?

**Comment by polyipseity** [comment]
As long as it's not red, it should be fine.

They are "normal" because the plugin tries to see what kind of link it is
(relative path, vault path, wikilink, or Markdown link?) by trying whether
the link is valid if interpreted as that kind of link.

**Comment by polyipseity** [comment]
Though if it does becoming too annoying, I could remove those log messages.

**Comment by stef-rausch** [comment]
I think that would be good for other users as well -- not seeing these messages that do not have an effect. 😉 

On the other hand, is there a "clean" way to write the path, which does not trigger the messages?

**Comment by polyipseity** [comment]
> I think that would be good for other users as well -- not seeing these messages that do not have an effect. 😉
> 
> On the other hand, is there a "clean" way to write the path, which does not trigger the messages?

There is no way to avoid triggering the message. But this is moot now because I have removed those statements in the latest release ([2.3.0](https://github.com/polyipseity/obsidian-modules/releases/2.3.0)).

**Comment by stef-rausch** [comment]
Thanks!
